version: "3.8"

services:
  mailgrass_backend:
    container_name: multicommerce_backend
    image: hridoyboss12/multicommerce:latest
#    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
#      - npm:/app
      - ./.env:/app/.env:ro
#      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - npm
    env_file: .env
#    build:
#      context: .
#      dockerfile: ./Dockerfile

volumes:
  npm:
networks:
  npm: