version: "3.8"

services:
  multicommerce_backend:
    container_name: multicommerce_backend
    image: hridoyboss12/multicommerce:latest
    restart: unless-stopped
    ports:
      - "8008:8000"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mailgrass_npm
    depends_on:
      - multicommerce_redis
    env_file: .env
  multicommerce_redis:
    container_name: multicommerce_redis
    image: redis:7.0-alpine
    restart: unless-stopped
    #    env_file: .env
    #    ports:
    #      - "6379:6379"
    #    command:
    #      - 'redis-server'
    networks:
      - npm
  celery:
    image: hridoyboss12/multicommerce:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mailgrass_npm
    depends_on:
      - multicommerce_redis
      - multicommerce_backend
    entrypoint: "celery -A core worker -P eventlet --autoscale=10,1 -l INFO"
  celery_beat:
    image: hridoyboss12/multicommerce:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mailgrass_npm
    depends_on:
      - multicommerce_redis
      - celery
    entrypoint: "celery -A core beat -l INFO"
volumes:
  npm:
  postgres:
networks:
  mailgrass_npm:
    external: true
