version: "3.8"

services:
  multicommerce_backend:
    container_name: multicommerce_backend
    image: hridoyboss12/multicommerce:latest
    restart: unless-stopped
    ports:
      - "8008:8000"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mailgrass_npm
    env_file: .env

networks:
  mailgrass_npm:
    external: true
