# Generated by Django 5.0.3 on 2024-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_cart_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revenue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
